name: docs


on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: Create config
        run: echo "export default {CLIENT_ID:'${{env.CLIENT_ID}}', CLIENT_SECRET:'${{env.CLIENT_SECRET}}'}" > ../config.js
        env:
          CLIENT_ID: ${{ secrets.GIT_TALK_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.GIT_TALK_CLIENT_SECRET }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-key: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.ouputs.cache-it != 'true'
        run: yarn --frozen-lockfile

      - name: Build VuePress site
        run: yarn docs:build

      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}